"use client";

import { useState, useEffect } from "react";
import { useParams } from "next/navigation";
import { cn } from "@/lib/utils";

type SharedFix = {
  id: string;
  repo: string;
  pr_number: number | null;
  comment_body: string | null;
  fix_response: string;
  diff: string | null;
  explainer: string | null;
  created_at: string;
};

export default function SharedFixPage() {
  const { id } = useParams<{ id: string }>();
  const [fix, setFix] = useState<SharedFix | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    fetch(`/api/fixes/${id}`)
      .then((r) => (r.ok ? r.json() : r.json().then((e) => Promise.reject(e.error))))
      .then(setFix)
      .catch((err) => setError(typeof err === "string" ? err : "Fix not found"))
      .finally(() => setLoading(false));
  }, [id]);

  if (loading) {
    return (
      <div className="mx-auto max-w-[800px] px-4 py-12">
        <div className="animate-pulse space-y-4">
          <div className="h-6 w-48 bg-surface-2 rounded" />
          <div className="h-4 w-96 bg-surface-2 rounded" />
          <div className="h-64 bg-surface-2 rounded" />
        </div>
      </div>
    );
  }

  if (error || !fix) {
    return (
      <div className="mx-auto max-w-[800px] px-4 py-12 text-center">
        <h1 className="serif text-[28px] text-paper">Fix not found</h1>
        <p className="mt-2 text-[13px] text-paper-dim">This shared fix link may have expired or been deleted.</p>
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-[800px] px-4 py-8">
      {/* Header */}
      <div className="border border-border bg-surface/40 px-5 py-4">
        <div className="flex items-center gap-3 mb-2">
          <span className="text-[10px] uppercase tracking-[0.15em] text-signal">shared fix</span>
          {fix.pr_number && (
            <span className="text-[10px] text-info border border-info/30 px-1.5 py-0.5">PR #{fix.pr_number}</span>
          )}
          <span className="text-[10px] text-paper-faint ml-auto">{new Date(fix.created_at).toLocaleString()}</span>
        </div>
        <h1 className="serif text-[22px] text-paper">{fix.repo}</h1>

        {fix.comment_body && (
          <div className="mt-3 px-3 py-2 border-l-2 border-signal/40 bg-ink/30 text-[12px] text-paper-dim">
            <span className="text-[9px] text-paper-faint uppercase tracking-[0.1em] block mb-1">Review comment</span>
            {fix.comment_body}
          </div>
        )}
      </div>

      {/* Explainer */}
      {fix.explainer && (
        <div className="mt-3 border border-ok/20 bg-ok/5 px-5 py-3">
          <span className="text-[9px] text-ok uppercase tracking-[0.1em] block mb-1">Why this fix</span>
          <p className="text-[12px] text-paper-dim whitespace-pre-wrap">{fix.explainer}</p>
        </div>
      )}

      {/* Diff */}
      {fix.diff && (
        <div className="mt-3 border border-border bg-ink/30">
          <div className="px-4 py-2 border-b border-border-soft flex items-center justify-between">
            <span className="text-[10px] text-paper-muted uppercase tracking-[0.15em]">Diff</span>
            <button
              onClick={() => {
                navigator.clipboard.writeText(fix.diff!);
                setCopied(true);
                setTimeout(() => setCopied(false), 2000);
              }}
              className="text-[10px] text-paper-faint hover:text-paper-muted transition"
            >
              {copied ? "copied" : "copy"}
            </button>
          </div>
          <pre className="px-4 py-3 text-[10.5px] font-mono leading-snug overflow-x-auto">
            {fix.diff.split("\n").map((line, i) => {
              let cls = "text-paper-dim";
              if (line.startsWith("+") && !line.startsWith("+++")) cls = "text-ok";
              else if (line.startsWith("-") && !line.startsWith("---")) cls = "text-alert";
              else if (line.startsWith("@@")) cls = "text-info";
              return <div key={i} className={cn("whitespace-pre-wrap", cls)}>{line || "\u00a0"}</div>;
            })}
          </pre>
        </div>
      )}

      {/* Full response */}
      <details className="mt-3 border border-border bg-surface/40">
        <summary className="px-4 py-2 cursor-pointer text-[11px] text-paper-muted hover:text-paper-dim transition">
          Full AI response
        </summary>
        <div className="px-4 py-3 text-[12px] text-paper-dim whitespace-pre-wrap break-words border-t border-border-soft">
          {fix.fix_response}
        </div>
      </details>

      {/* Footer */}
      <div className="mt-6 text-center text-[11px] text-paper-faint">
        Generated by opensrcer
      </div>
    </div>
  );
}
